# Линейная алгебра.

## Змейка m x n

In [1]:
import numpy as np


def snake(m, n):
    matrix = np.arange(1, m * n + 1).reshape(m, n)

    for stroka in range(1, m, 2):
        matrix[stroka] = matrix[stroka][::-1]

    return matrix

In [2]:
print(snake(3, 4))

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


## Продукты

In [3]:
import numpy as np


def calculate(products, cook):
    rez_matrix = products * np.array(cook).reshape(-1, 1)

    count_products = np.ceil(np.sum(rez_matrix, axis=0))

    print(f'Молоко, литры: {int(count_products[0])}')
    print(f'Яйца, штуки: {int(count_products[1])}')
    print(f'Мука, кг: {int(count_products[2])}')

In [4]:
products = np.array([
    [0.1, 2, 0.05],
    [0.2, 1, 0.2],
    [0.5, 3, 0.3]])

cook = [10, 32, 8]

calculate(products, cook)

Молоко, литры: 12
Яйца, штуки: 76
Мука, кг: 10


## K ближайших пингвинов

In [6]:

import pandas as pd
import numpy as np

data_frame = pd.read_csv('/Users/artemvorobchenko/Downloads/penguins (2).csv')

data_frame.dropna(inplace=True)

new_df = np.array(data_frame[['bill_length_mm', 'bill_depth_mm']])


def evklid_dist(n, k, new_df=new_df):
    dist = np.sqrt(((new_df - new_df[n]) ** 2).sum(axis=1))
    new_df = np.column_stack((new_df, dist))
    new_df = new_df[new_df[:, 2].argsort()]
    rez = np.delete(new_df[1:k + 1], 2, axis=1)

    for row in rez:
        print(row)


n = int(input()) # 0
k = int(input()) # 5

evklid_dist(n, k)

[39.  18.7]
[39.2 18.6]
[38.9 18.8]
[38.7 19. ]
[39.6 18.8]
