# Линейные модели

## One hot encoding

In [3]:
import numpy as np

In [4]:
def onehot_encoding(arr):
    val, index_in_ohe = np.unique(arr, return_inverse=True)
    ohe_matrix = np.zeros((len(arr), len(val)), dtype=np.int64)

    for row in range(len(ohe_matrix)):
        ohe_matrix[row][index_in_ohe[row]] = 1

    return ohe_matrix.astype(int)

In [5]:
x = np.array([3, 2, 2, 1])
print(onehot_encoding(x))

[[0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


## MinMax Scaler

In [7]:
def minmax_scale(arr):
    denominator = arr.max(axis=0) - arr.min(axis=0)
    denominator[denominator == 0] = 1
    rez = (arr - arr.min(axis=0)) / denominator

    return rez

In [8]:
X = np.array([[1, 2], [2, 1]])
print(minmax_scale(X))

[[0. 1.]
 [1. 0.]]
