# Линейные модели

## One hot encoding

In [21]:
import numpy as np
import pandas as pd

In [22]:
class onehot_encoder:
    def __init__(self, drop_column=False):
        self.features_unique = dict()
        self.drop_column = drop_column

    def fit(self, arr, columns):
        for col in columns:
            self.features_unique[col] = np.unique(arr[col])

    def transform(self, arr, columns):
        final_matrix = []

        for col in columns:
            index_in_unique = np.searchsorted(self.features_unique[col], arr[col])
            ohe_matrix = np.zeros((len(arr[col]), len(self.features_unique[col])))

            for row in range(len(ohe_matrix)):
                ohe_matrix[row][index_in_unique[row]] = 1

            if self.drop_column:
                ohe_matrix = ohe_matrix[:,1:]

            final_matrix.append(ohe_matrix)

        return np.hstack(final_matrix)

    def fit_transform(self, arr, columns):
        self.fit(arr, columns)
        return self.transform(arr, columns)

In [23]:
x = np.array([3, 2, 2, 1])
df_x = pd.DataFrame(x, columns=['my_feature'])

encoder = onehot_encoder(drop_column=False)
result = encoder.fit_transform(df_x, ['my_feature'])

In [24]:
print("Оригинал:", x)
print("Результат OHE:\n", result)

Оригинал: [3 2 2 1]
Результат OHE:
 [[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


## MinMax Scaler

In [25]:
class minmax_scale:
    def __init__(self):
        self.min_val = None
        self.max_val = None
        self.denominator = None

    def fit(self, data):
        data = np.array(data)
        self.min_val = data.min(axis=0)
        self.max_val = data.max(axis=0)
        self.denominator = self.max_val - self.min_val
        self.denominator = np.where(self.denominator == 0, 1, self.denominator)
        return self

    def transform(self, data):
        data = np.array(data)
        data = np.where(np.isinf(data), self.max_val, data)
        return ((data - self.min_val) / self.denominator)

    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [26]:
X = np.array([[1, 2], [2, 1]])
scaler = minmax_scale()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[0. 1.]
 [1. 0.]]
